#!/usr/bin/env python
# -*- encoding: utf-8 -*-
# Created on 2018-11-02 00:14:15
# Project: trip

from pyspider.libs.base_handler import *
import re
import pymongo

class Handler(BaseHandler):
    crawl_config = {
    }
    
    client=pymongo.MongoClient('localhost')
    db=client['trip']
    @every(minutes=24 * 60)
    def on_start(self):
        self.crawl('https://www.tripadvisor.cn/Attractions-g297442-Activities-Suzhou_Jiangsu.html', callback=self.index_page)

    @config(age=10 * 24 * 60 * 60)
    def index_page(self, response):
        for each in response.doc('.attraction_element .listing_title > a').items():
            self.crawl(each.attr.href, callback=self.detail_page)
        next =response.doc('.nav.next').attr('href')
        self.crawl(next,callback=self.index_page)
            
            
    @config(priority=2)
    def detail_page(self, response):
        return {
            "name": response.doc('.h1').text().strip(),
            "address":response.doc('.street-address').text(),
            "views":response.doc('a > .reviewCount').text()[:-4],
            "rank":response.doc('b > span').text(),
            "overallRating":response.doc('.overallRating').text(),
            "OpenHours":response.doc('.AboutSection__sectionWrapper--34W6L > div').text()[7:]       
        }
    
    def on_result(self,result):
        if result:
             self.save_mongo(result)
            
    def save_mongo(self,result):
        if self.db['SuZhou'].insert(result):
            print('save to mongo',result)
